export const firstColData = [
  {
    uMM: "ဎ",
    lMM: "ၐ",
    eng: "~",
    lowerKeyCode: 192,
    upperKeyCode: 301,
  },
  {
    uMM: "ဍ",
    lMM: "၁",
    eng: "1",
    lowerKeyCode: 49,
    upperKeyCode: 302,
  },
  {
    uMM: "ၒ",
    lMM: "၂",
    eng: "2",
    lowerKeyCode: 50,
    upperKeyCode: 303,
  },
  {
    uMM: "ဋ",
    lMM: "၃",
    eng: "3",
    lowerKeyCode: 51,
    upperKeyCode: 304,
  },
  {
    uMM: "ၓ",
    lMM: "၄",
    eng: "4",
    lowerKeyCode: 52,
    upperKeyCode: 305,
  },
  {
    uMM: "ၔ",
    lMM: "၅",
    eng: "5",
    lowerKeyCode: 53,
    upperKeyCode: 306,
  },
  {
    uMM: "ၕ",
    lMM: "၆",
    eng: "6",
    lowerKeyCode: 54,
    upperKeyCode: 307,
  },
  {
    uMM: "ရ",
    lMM: "၇",
    eng: "7",
    lowerKeyCode: 55,
    upperKeyCode: 308,
  },
  {
    uMM: "*",
    lMM: "၈",
    eng: "8",
    lowerKeyCode: 56,
    upperKeyCode: 309,
  },
  {
    uMM: "(",
    lMM: "၉",
    eng: "9",
    lowerKeyCode: 57,
    upperKeyCode: 310,
  },
  {
    uMM: ")",
    lMM: "၀",
    eng: "0",
    lowerKeyCode: 48,
    upperKeyCode: 311,
  },
  {
    uMM: "-",
    lMM: "_",
    eng: "-",
    lowerKeyCode: 404,
    upperKeyCode: 404,
  },
  {
    uMM: "+",
    lMM: "=",
    eng: "=",
    lowerKeyCode: 404,
    upperKeyCode: 404,
  },
];

export const secondColData = [
  {
    uMM: "ဈ",
    lMM: "ဆ",
    eng: "Q",
    lowerKeyCode: 81,
    upperKeyCode: 312,
  },
  {
    uMM: "ဝ",
    lMM: "တ",
    eng: "W",
    lowerKeyCode: 87,
    upperKeyCode: 313,
  },
  {
    uMM: "ဣ",
    lMM: "န",
    eng: "E",
    lowerKeyCode: 69,
    upperKeyCode: 314,
  },
  {
    uMM: "၎",
    lMM: "မ",
    eng: "R",
    lowerKeyCode: 82,
    upperKeyCode: 315,
  },
  {
    uMM: "ဤ",
    lMM: "အ",
    eng: "T",
    lowerKeyCode: 84,
    upperKeyCode: 316,
  },
  {
    uMM: "၌",
    lMM: "ပ",
    eng: "Y",
    lowerKeyCode: 89,
    upperKeyCode: 317,
  },
  {
    uMM: "ဥ",
    lMM: "က",
    eng: "U",
    lowerKeyCode: 85,
    upperKeyCode: 318,
  },
  {
    uMM: "၍",
    lMM: "င",
    eng: "I",
    lowerKeyCode: 73,
    upperKeyCode: 319,
  },
  {
    uMM: "ဿ",
    lMM: "သ",
    eng: "O",
    lowerKeyCode: 79,
    upperKeyCode: 320,
  },
  {
    uMM: "ဏ",
    lMM: "စ",
    eng: "P",
    lowerKeyCode: 80,
    upperKeyCode: 321,
  },
  {
    uMM: "ဧ",
    lMM: "ဟ",
    eng: "{",
    lowerKeyCode: 219,
    upperKeyCode: 322,
  },
  {
    uMM: "ဪ",
    lMM: "ဩ",
    eng: "}",
    lowerKeyCode: 221,
    upperKeyCode: 323,
  },
  {
    uMM: "ၑ",
    lMM: "၏",
    eng: "\\",
    lowerKeyCode: 220,
    upperKeyCode: 324,
  },
];

export const thirdColData = [
  {
    uMM: "ဗ",
    lMM: "‌ေ",
    eng: "A",
    lowerKeyCode: 65,
    upperKeyCode: 325,
  },
  {
    uMM: "ှ",
    lMM: "ျ",
    eng: "S",
    lowerKeyCode: 83,
    upperKeyCode: 326,
  },
  {
    uMM: "ီ",
    lMM: "ိ",
    eng: "D",
    lowerKeyCode: 68,
    upperKeyCode: 327,
  },
  {
    uMM: "္",
    lMM: "်",
    eng: "F",
    lowerKeyCode: 70,
    upperKeyCode: 328,
  },
  {
    uMM: "ွ",
    lMM: "ါ",
    eng: "G",
    lowerKeyCode: 71,
    upperKeyCode: 329,
  },
  {
    uMM: "ံ",
    lMM: "့",
    eng: "H",
    lowerKeyCode: 72,
    upperKeyCode: 330,
  },
  {
    uMM: "ဲ",
    lMM: "ြ",
    eng: "J",
    lowerKeyCode: 74,
    upperKeyCode: 331,
  },
  {
    uMM: "ဒ",
    lMM: "ု",
    eng: "K",
    lowerKeyCode: 75,
    upperKeyCode: 332,
  },
  {
    uMM: "ဓ",
    lMM: "ူ",
    eng: "L",
    lowerKeyCode: 76,
    upperKeyCode: 333,
  },
  {
    uMM: "ဂ",
    lMM: "း",
    eng: ";",
    lowerKeyCode: 186,
    upperKeyCode: 334,
  },
  {
    uMM: '"',
    lMM: "'",
    eng: "'",
    lowerKeyCode: 222,
    upperKeyCode: 335,
  },
];

export const fouthColData = [
  {
    uMM: "ဇ",
    lMM: "ဖ",
    eng: "Z",
    lowerKeyCode: 90,
    upperKeyCode: 336,
  },
  {
    uMM: "ဌ",
    lMM: "ထ",
    eng: "X",
    lowerKeyCode: 88,
    upperKeyCode: 337,
  },
  {
    uMM: "ဃ",
    lMM: "ခ",
    eng: "C",
    lowerKeyCode: 67,
    upperKeyCode: 338,
  },
  {
    uMM: "ဠ",
    lMM: "လ",
    eng: "V",
    lowerKeyCode: 86,
    upperKeyCode: 339,
  },
  {
    uMM: "ယ",
    lMM: "ဘ",
    eng: "B",
    lowerKeyCode: 66,
    upperKeyCode: 340,
  },
  {
    uMM: "ဉ",
    lMM: "ည",
    eng: "N",
    lowerKeyCode: 78,
    upperKeyCode: 341,
  },
  {
    uMM: "ဦ",
    lMM: "ာ",
    eng: "M",
    lowerKeyCode: 77,
    upperKeyCode: 342,
  },
  {
    uMM: "၊",
    lMM: ",",
    eng: ",",
    lowerKeyCode: 188,
    upperKeyCode: 343,
  },
  {
    uMM: "။",
    lMM: ".",
    eng: ".",
    lowerKeyCode: 190,
    upperKeyCode: 344,
  },
  {
    uMM: "?",
    lMM: "/",
    eng: "/",
    lowerKeyCode: 404,
    upperKeyCode: 404,
  },
];

export const dashCharData = [
  "ှ",
  "ျ",
  "ီ",
  "ိ",
  "္",
  "်",
  "ွ",
  "ါ",
  "့",
  "ံ",
  "ဲ",
  "ြ",
  "ု",
  "ူ",
  "း",
];

export const allCharData = [
  { char: "ၐ", keyCode: 192 },
  { char: "၁", keyCode: 49 },
  { char: "၂", keyCode: 50 },
  { char: "၃", keyCode: 51 },
  { char: "၄", keyCode: 52 },
  { char: "၅", keyCode: 53 },
  { char: "၆", keyCode: 54 },
  { char: "၇", keyCode: 55 },
  { char: "၈", keyCode: 56 },
  { char: "၉", keyCode: 57 },
  { char: "၀", keyCode: 48 },
  { char: "ဎ", keyCode: 301 },
  { char: "ဍ", keyCode: 302 },
  { char: "ၒ", keyCode: 303 },
  { char: "ဋ", keyCode: 304 },
  { char: "ၓ", keyCode: 305 },
  { char: "ၔ", keyCode: 306 },
  { char: "ၕ", keyCode: 307 },
  { char: "ရ", keyCode: 308 },
  { char: "*", keyCode: 309 },
  { char: "(", keyCode: 310 },
  { char: ")", keyCode: 311 },
  { char: "ဈ", keyCode: 312 },
  { char: "ဝ", keyCode: 313 },
  { char: "ဣ", keyCode: 314 },
  { char: "၎", keyCode: 315 },
  { char: "ဤ", keyCode: 316 },
  { char: "၌", keyCode: 317 },
  { char: "ဥ", keyCode: 318 },
  { char: "၍", keyCode: 319 },
  { char: "ဿ", keyCode: 320 },
  { char: "ဏ", keyCode: 321 },
  { char: "ဧ", keyCode: 322 },
  { char: "ဪ", keyCode: 323 },
  { char: "ၑ", keyCode: 324 },
  { char: "ဆ", keyCode: 81 },
  { char: "တ", keyCode: 87 },
  { char: "န", keyCode: 69 },
  { char: "မ", keyCode: 82 },
  { char: "အ", keyCode: 84 },
  { char: "ပ", keyCode: 89 },
  { char: "က", keyCode: 85 },
  { char: "င", keyCode: 73 },
  { char: "သ", keyCode: 79 },
  { char: "စ", keyCode: 80 },
  { char: "ဟ", keyCode: 219 },
  { char: "ဩ", keyCode: 221 },
  { char: "၏", keyCode: 220 },
  { char: "ဗ", keyCode: 325 },
  { char: "ှ", keyCode: 326 },
  { char: "ီ", keyCode: 327 },
  { char: "္", keyCode: 328 },
  { char: "ွ", keyCode: 329 },
  { char: "ံ", keyCode: 330 },
  { char: "ဲ", keyCode: 331 },
  { char: "ဒ", keyCode: 332 },
  { char: "ဓ", keyCode: 333 },
  { char: "ဂ", keyCode: 334 },
  { char: '"', keyCode: 335 },
  { char: "‌ေ", keyCode: 65 },
  { char: "ျ", keyCode: 83 },
  { char: "ိ", keyCode: 68 },
  { char: "်", keyCode: 70 },
  { char: "ါ", keyCode: 71 },
  { char: "့", keyCode: 72 },
  { char: "ြ", keyCode: 74 },
  { char: "ု", keyCode: 75 },
  { char: "ူ", keyCode: 76 },
  { char: "း", keyCode: 186 },
  { char: "'", keyCode: 222 },
  { char: "ဇ", keyCode: 336 },
  { char: "ဌ", keyCode: 337 },
  { char: "ဃ", keyCode: 338 },
  { char: "ဠ", keyCode: 339 },
  { char: "ယ", keyCode: 340 },
  { char: "ဉ", keyCode: 341 },
  { char: "ဦ", keyCode: 342 },
  { char: "၊", keyCode: 343 },
  { char: "။", keyCode: 344 },
  { char: "?", keyCode: 404 },
  { char: "ဖ", keyCode: 90 },
  { char: "ထ", keyCode: 88 },
  { char: "ခ", keyCode: 67 },
  { char: "လ", keyCode: 86 },
  { char: "ဘ", keyCode: 66 },
  { char: "ည", keyCode: 78 },
  { char: "ာ", keyCode: 77 },
  { char: ",", keyCode: 188 },
  { char: ".", keyCode: 190 },
  { char: "/", keyCode: 404 },
  { char: " ", keyCode: 32 },
];

export const fakeKeyboardItem = {
  uMM: "",
  lMM: "",
  eng: "",
  lowerKeyCode: "",
  upperKeyCode: "",
};
